<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<AssemblyName>console</AssemblyName>
		<Copyright>© Synentra. All rights reserved.</Copyright>
		<RepositoryUrl>https://github.com/synentra/console</RepositoryUrl>
		<Title>Synentra Console</Title>
		<Company>Synentra</Company>
		<Description>Web-based management console for monitoring Synentra gateway.</Description>
		<Authors>Synentra</Authors>
		<PackageProjectUrl>https://synentra.io</PackageProjectUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugSymbols>False</DebugSymbols>
		<DebugType>None</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
		<PackageReference Include="MudBlazor" Version="8.6.0" />
	</ItemGroup>

</Project>
